use std::collections::BTreeMap;

use super::anthropic_model_catalog::{
    AnthropicCatalogProvider, AnthropicModelCatalog, AnthropicModelCatalogEntry,
    AnthropicModelPricing, AnthropicModelStatus,
};
use super::provider_config::ProviderAuth;

pub(crate) fn generated_anthropic_model_catalog() -> AnthropicModelCatalog {
    AnthropicModelCatalog {
        provider: AnthropicCatalogProvider {
            id: "anthropic".to_string(),
            display_name: "Anthropic".to_string(),
            base_url: "https://api.anthropic.com/v1".to_string(),
            protocol: "anthropic_messages".to_string(),
            source_url: "https://docs.anthropic.com/en/docs/models-overview".to_string(),
            auth: ProviderAuth::ApiKeyEnv {
                keys: vec!["ANTHROPIC_API_KEY".to_string()],
            },
        },
        models: BTreeMap::from([
            (
                "claude-1.0".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-1.0".to_string(),
                    api_model_id: "claude-1.0".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("September 4, 2024".to_string()),
                    retirement_date: Some("November 6, 2024".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-haiku-4-5-20251001".to_string()),
                },
            ),
            (
                "claude-1.1".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-1.1".to_string(),
                    api_model_id: "claude-1.1".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("September 4, 2024".to_string()),
                    retirement_date: Some("November 6, 2024".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-haiku-4-5-20251001".to_string()),
                },
            ),
            (
                "claude-1.2".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-1.2".to_string(),
                    api_model_id: "claude-1.2".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("September 4, 2024".to_string()),
                    retirement_date: Some("November 6, 2024".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-haiku-4-5-20251001".to_string()),
                },
            ),
            (
                "claude-1.3".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-1.3".to_string(),
                    api_model_id: "claude-1.3".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("September 4, 2024".to_string()),
                    retirement_date: Some("November 6, 2024".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-haiku-4-5-20251001".to_string()),
                },
            ),
            (
                "claude-2.0".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-2.0".to_string(),
                    api_model_id: "claude-2.0".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("January 21, 2025".to_string()),
                    retirement_date: Some("July 21, 2025".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-opus-4-6".to_string()),
                },
            ),
            (
                "claude-2.1".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-2.1".to_string(),
                    api_model_id: "claude-2.1".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("January 21, 2025".to_string()),
                    retirement_date: Some("July 21, 2025".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-opus-4-6".to_string()),
                },
            ),
            (
                "claude-3-5-haiku-20241022".to_string(),
                AnthropicModelCatalogEntry {
                    source_url: "https://docs.anthropic.com/en/docs/models-overview".to_string(),
                    lifecycle_source_url: Some(
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    ),
                    display_name: "claude-3-5-haiku-20241022".to_string(),
                    api_model_id: "claude-3-5-haiku-20241022".to_string(),
                    api_alias: Some("claude-3-5-haiku-latest".to_string()),
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("December 19, 2025".to_string()),
                    retirement_date: Some("February 19, 2026".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-haiku-4-5-20251001".to_string()),
                },
            ),
            (
                "claude-3-5-sonnet-20240620".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-3-5-sonnet-20240620".to_string(),
                    api_model_id: "claude-3-5-sonnet-20240620".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("August 13, 2025".to_string()),
                    retirement_date: Some("October 28, 2025".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-opus-4-6".to_string()),
                },
            ),
            (
                "claude-3-5-sonnet-20241022".to_string(),
                AnthropicModelCatalogEntry {
                    source_url: "https://docs.anthropic.com/en/docs/models-overview".to_string(),
                    lifecycle_source_url: Some(
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    ),
                    display_name: "claude-3-5-sonnet-20241022".to_string(),
                    api_model_id: "claude-3-5-sonnet-20241022".to_string(),
                    api_alias: Some("claude-3-5-sonnet-latest".to_string()),
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("August 13, 2025".to_string()),
                    retirement_date: Some("October 28, 2025".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-opus-4-6".to_string()),
                },
            ),
            (
                "claude-3-7-sonnet-20250219".to_string(),
                AnthropicModelCatalogEntry {
                    source_url: "https://docs.anthropic.com/en/docs/models-overview".to_string(),
                    lifecycle_source_url: Some(
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    ),
                    display_name: "claude-3-7-sonnet-20250219".to_string(),
                    api_model_id: "claude-3-7-sonnet-20250219".to_string(),
                    api_alias: Some("claude-3-7-sonnet-latest".to_string()),
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("October 28, 2025".to_string()),
                    retirement_date: Some("February 19, 2026".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-opus-4-6".to_string()),
                },
            ),
            (
                "claude-3-haiku-20240307".to_string(),
                AnthropicModelCatalogEntry {
                    source_url: "https://docs.anthropic.com/en/docs/models-overview".to_string(),
                    lifecycle_source_url: Some(
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    ),
                    display_name: "claude-3-haiku-20240307".to_string(),
                    api_model_id: "claude-3-haiku-20240307".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Deprecated,
                    deprecated_on: Some("February 19, 2026".to_string()),
                    retirement_date: Some("April 20, 2026".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-haiku-4-5-20251001".to_string()),
                },
            ),
            (
                "claude-3-opus-20240229".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-3-opus-20240229".to_string(),
                    api_model_id: "claude-3-opus-20240229".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("June 30, 2025".to_string()),
                    retirement_date: Some("January 5, 2026".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-opus-4-6".to_string()),
                },
            ),
            (
                "claude-3-sonnet-20240229".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-3-sonnet-20240229".to_string(),
                    api_model_id: "claude-3-sonnet-20240229".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("January 21, 2025".to_string()),
                    retirement_date: Some("July 21, 2025".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-opus-4-6".to_string()),
                },
            ),
            (
                "claude-haiku-4-5-20251001".to_string(),
                AnthropicModelCatalogEntry {
                    source_url: "https://docs.anthropic.com/en/docs/models-overview".to_string(),
                    lifecycle_source_url: Some(
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    ),
                    display_name: "Claude Haiku 4.5".to_string(),
                    api_model_id: "claude-haiku-4-5-20251001".to_string(),
                    api_alias: Some("claude-haiku-4-5".to_string()),
                    bedrock_model_id: Some("anthropic.claude-haiku-4-5-20251001-v1:0".to_string()),
                    vertex_model_id: Some("claude-haiku-4-5@20251001".to_string()),
                    description: Some(
                        "The fastest model with near-frontier intelligence.".to_string(),
                    ),
                    input_modalities: vec!["text".to_string(), "image".to_string()],
                    output_modalities: vec!["text".to_string()],
                    features: BTreeMap::from([
                        ("adaptive_thinking".to_string(), false),
                        ("extended_thinking".to_string(), true),
                        ("image_input".to_string(), true),
                        ("multilingual".to_string(), true),
                        ("priority_tier".to_string(), true),
                        ("text_input".to_string(), true),
                        ("text_output".to_string(), true),
                        ("vision".to_string(), true),
                    ]),
                    comparative_latency: Some("fastest".to_string()),
                    context_window_tokens: Some(200000),
                    beta_context_window_tokens: None,
                    max_output_tokens: Some(64000),
                    reliable_knowledge_cutoff: Some("Feb 2025".to_string()),
                    training_data_cutoff: Some("Jul 2025".to_string()),
                    beta_headers: BTreeMap::new(),
                    pricing: Some(AnthropicModelPricing {
                        input_usd_per_mtok: "1".to_string(),
                        output_usd_per_mtok: "5".to_string(),
                    }),
                    status: AnthropicModelStatus::Active,
                    deprecated_on: None,
                    retirement_date: None,
                    not_retired_before: Some("November 1, 2026".to_string()),
                    recommended_replacement: None,
                },
            ),
            (
                "claude-instant-1.0".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-instant-1.0".to_string(),
                    api_model_id: "claude-instant-1.0".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("September 4, 2024".to_string()),
                    retirement_date: Some("November 6, 2024".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-haiku-4-5-20251001".to_string()),
                },
            ),
            (
                "claude-instant-1.1".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-instant-1.1".to_string(),
                    api_model_id: "claude-instant-1.1".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("September 4, 2024".to_string()),
                    retirement_date: Some("November 6, 2024".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-haiku-4-5-20251001".to_string()),
                },
            ),
            (
                "claude-instant-1.2".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-instant-1.2".to_string(),
                    api_model_id: "claude-instant-1.2".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Retired,
                    deprecated_on: Some("September 4, 2024".to_string()),
                    retirement_date: Some("November 6, 2024".to_string()),
                    not_retired_before: None,
                    recommended_replacement: Some("claude-haiku-4-5-20251001".to_string()),
                },
            ),
            (
                "claude-opus-4-1-20250805".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-opus-4-1-20250805".to_string(),
                    api_model_id: "claude-opus-4-1-20250805".to_string(),
                    api_alias: Some("claude-opus-4-1".to_string()),
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Active,
                    deprecated_on: None,
                    retirement_date: None,
                    not_retired_before: Some("August 5, 2026".to_string()),
                    recommended_replacement: None,
                },
            ),
            (
                "claude-opus-4-20250514".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-opus-4-20250514".to_string(),
                    api_model_id: "claude-opus-4-20250514".to_string(),
                    api_alias: Some("claude-opus-4-0".to_string()),
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Active,
                    deprecated_on: None,
                    retirement_date: None,
                    not_retired_before: Some("May 22, 2026".to_string()),
                    recommended_replacement: None,
                },
            ),
            (
                "claude-opus-4-5-20251101".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-opus-4-5-20251101".to_string(),
                    api_model_id: "claude-opus-4-5-20251101".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Active,
                    deprecated_on: None,
                    retirement_date: None,
                    not_retired_before: Some("November 1, 2026".to_string()),
                    recommended_replacement: None,
                },
            ),
            (
                "claude-opus-4-6".to_string(),
                AnthropicModelCatalogEntry {
                    source_url: "https://docs.anthropic.com/en/docs/models-overview".to_string(),
                    lifecycle_source_url: Some(
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    ),
                    display_name: "Claude Opus 4.6".to_string(),
                    api_model_id: "claude-opus-4-6".to_string(),
                    api_alias: Some("claude-opus-4-6".to_string()),
                    bedrock_model_id: Some("anthropic.claude-opus-4-6-v1".to_string()),
                    vertex_model_id: Some("claude-opus-4-6".to_string()),
                    description: Some(
                        "The most intelligent model for building agents and coding.".to_string(),
                    ),
                    input_modalities: vec!["text".to_string(), "image".to_string()],
                    output_modalities: vec!["text".to_string()],
                    features: BTreeMap::from([
                        ("adaptive_thinking".to_string(), true),
                        ("extended_thinking".to_string(), true),
                        ("image_input".to_string(), true),
                        ("multilingual".to_string(), true),
                        ("priority_tier".to_string(), true),
                        ("text_input".to_string(), true),
                        ("text_output".to_string(), true),
                        ("vision".to_string(), true),
                    ]),
                    comparative_latency: Some("moderate".to_string()),
                    context_window_tokens: Some(200000),
                    beta_context_window_tokens: Some(1000000),
                    max_output_tokens: Some(128000),
                    reliable_knowledge_cutoff: Some("May 2025".to_string()),
                    training_data_cutoff: Some("Aug 2025".to_string()),
                    beta_headers: BTreeMap::from([(
                        "context_1m".to_string(),
                        "context-1m-2025-08-07".to_string(),
                    )]),
                    pricing: Some(AnthropicModelPricing {
                        input_usd_per_mtok: "5".to_string(),
                        output_usd_per_mtok: "25".to_string(),
                    }),
                    status: AnthropicModelStatus::Active,
                    deprecated_on: None,
                    retirement_date: None,
                    not_retired_before: Some("February 5, 2027".to_string()),
                    recommended_replacement: None,
                },
            ),
            (
                "claude-sonnet-4-20250514".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-sonnet-4-20250514".to_string(),
                    api_model_id: "claude-sonnet-4-20250514".to_string(),
                    api_alias: Some("claude-sonnet-4-0".to_string()),
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Active,
                    deprecated_on: None,
                    retirement_date: None,
                    not_retired_before: Some("May 22, 2026".to_string()),
                    recommended_replacement: None,
                },
            ),
            (
                "claude-sonnet-4-5-20250929".to_string(),
                AnthropicModelCatalogEntry {
                    source_url:
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    lifecycle_source_url: None,
                    display_name: "claude-sonnet-4-5-20250929".to_string(),
                    api_model_id: "claude-sonnet-4-5-20250929".to_string(),
                    api_alias: None,
                    bedrock_model_id: None,
                    vertex_model_id: None,
                    description: None,
                    input_modalities: vec![],
                    output_modalities: vec![],
                    features: BTreeMap::new(),
                    comparative_latency: None,
                    context_window_tokens: None,
                    beta_context_window_tokens: None,
                    max_output_tokens: None,
                    reliable_knowledge_cutoff: None,
                    training_data_cutoff: None,
                    beta_headers: BTreeMap::new(),
                    pricing: None,
                    status: AnthropicModelStatus::Active,
                    deprecated_on: None,
                    retirement_date: None,
                    not_retired_before: Some("September 29, 2026".to_string()),
                    recommended_replacement: None,
                },
            ),
            (
                "claude-sonnet-4-6".to_string(),
                AnthropicModelCatalogEntry {
                    source_url: "https://docs.anthropic.com/en/docs/models-overview".to_string(),
                    lifecycle_source_url: Some(
                        "https://docs.anthropic.com/en/docs/about-claude/model-deprecations"
                            .to_string(),
                    ),
                    display_name: "Claude Sonnet 4.6".to_string(),
                    api_model_id: "claude-sonnet-4-6".to_string(),
                    api_alias: Some("claude-sonnet-4-6".to_string()),
                    bedrock_model_id: Some("anthropic.claude-sonnet-4-6".to_string()),
                    vertex_model_id: Some("claude-sonnet-4-6".to_string()),
                    description: Some(
                        "The best combination of speed and intelligence.".to_string(),
                    ),
                    input_modalities: vec!["text".to_string(), "image".to_string()],
                    output_modalities: vec!["text".to_string()],
                    features: BTreeMap::from([
                        ("adaptive_thinking".to_string(), true),
                        ("extended_thinking".to_string(), true),
                        ("image_input".to_string(), true),
                        ("multilingual".to_string(), true),
                        ("priority_tier".to_string(), true),
                        ("text_input".to_string(), true),
                        ("text_output".to_string(), true),
                        ("vision".to_string(), true),
                    ]),
                    comparative_latency: Some("fast".to_string()),
                    context_window_tokens: Some(200000),
                    beta_context_window_tokens: Some(1000000),
                    max_output_tokens: Some(64000),
                    reliable_knowledge_cutoff: Some("Aug 2025".to_string()),
                    training_data_cutoff: Some("Jan 2026".to_string()),
                    beta_headers: BTreeMap::from([(
                        "context_1m".to_string(),
                        "context-1m-2025-08-07".to_string(),
                    )]),
                    pricing: Some(AnthropicModelPricing {
                        input_usd_per_mtok: "3".to_string(),
                        output_usd_per_mtok: "15".to_string(),
                    }),
                    status: AnthropicModelStatus::Active,
                    deprecated_on: None,
                    retirement_date: None,
                    not_retired_before: Some("February 23, 2027".to_string()),
                    recommended_replacement: None,
                },
            ),
        ]),
    }
}
